create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  author text not null default 'Anônimo',
  text text not null,
  status text not null default 'PENDING' check (status in ('PENDING', 'ANSWERED', 'PREMIUM')),
  answer text,
  video_url text,
  created_at timestamptz not null default now()
);

alter table public.questions enable row level security;

drop policy if exists "questions_public_all" on public.questions;
create policy "questions_public_all"
  on public.questions
  for all
  to anon, authenticated
  using (true)
  with check (true);
